name: Build-Publish-Dev

on:
  workflow_dispatch:

  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read
  packages: write

env:
  IMAGE_NAME: react-webapp

jobs:

  build-and-publish:

    runs-on: xyz-abc-ddd

    container:
      image: GHCR_MAVEN_KANIKO_IMAGE_PLACEHOLDER

    steps:

      ####################################################
      # Checkout Source
      ####################################################

      - name: Checkout
        uses: actions/checkout@v4

      ####################################################
      # Generate Image Tag
      ####################################################

      - name: Generate Image Tag
        run: |
          IMAGE_TAG=$(echo ${GITHUB_SHA} | cut -c1-8)
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      ####################################################
      # Verify Kaniko
      ####################################################

      - name: Verify Kaniko
        run: |
          ls -l /kaniko
          /kaniko/executor version

      ####################################################
      # Create ACR Authentication
      ####################################################

      - name: Create ACR Auth Config
        run: |

          mkdir -p /kaniko/.docker

          AUTH=$(echo -n "${{ secrets.AZURE_CLIENT_ID }}:${{ secrets.AZURE_CLIENT_SECRET }}" | base64 -w 0)

          cat > /kaniko/.docker/config.json <<EOF
          {
            "auths": {
              "${{ secrets.ACR_LOGIN_SERVER }}": {
                "auth": "${AUTH}"
              }
            }
          }
          EOF

      ####################################################
      # Build and Push using Kaniko
      ####################################################

      - name: Build And Push
        run: |
          /kaniko/executor \
            --context="${GITHUB_WORKSPACE}" \
            --dockerfile="${GITHUB_WORKSPACE}/Dockerfile" \
            --destination="${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG}" \
            --oci-layout-path=/kaniko/oci-layout

      ####################################################
      # Summary
      ####################################################

      - name: Build Summary
        run: |
          echo "Image successfully pushed:"
          echo "${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG}"
          - name: Verify Image In ACR
 
      - name: Image tag details in the ACR
        run: |
          az acr repository show-tags \
          --name ${{ secrets.ACR_NAME }} \
          --repository react-webapp \
          -o table
