name: Build-Publish-Dev

on:
  workflow_dispatch:

  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read
  packages: write

env:
  IMAGE_NAME: react-webapp

jobs:

  build-and-publish:

    runs-on: xyz-abc-ddd

    steps:

      ####################################################
      # Checkout
      ####################################################

      - name: Checkout
        uses: actions/checkout@v4

      ####################################################
      # Azure Login
      ####################################################

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
            }

      ####################################################
      # Generate Tag
      ####################################################

      - name: Generate Image Tag
        run: |
          IMAGE_TAG=$(echo ${GITHUB_SHA} | cut -c1-8)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      ####################################################
      # Create Docker Authentication Config
      ####################################################

      - name: Create Docker Config
        shell: bash
        run: |

          mkdir -p ~/.docker

          GHCR_AUTH=$(echo -n "${{ github.actor }}:${{ github.token }}" | base64 -w 0)

          ACR_AUTH=$(echo -n "${{ secrets.AZURE_CLIENT_ID }}:${{ secrets.AZURE_CLIENT_SECRET }}" | base64 -w 0)

          cat > ~/.docker/config.json <<EOF
          {
            "auths": {
              "ghcr.io": {
                "auth": "${GHCR_AUTH}"
              },
              "${{ secrets.ACR_LOGIN_SERVER }}": {
                "auth": "${ACR_AUTH}"
              }
            }
          }
          EOF

      ####################################################
      # Build and Push Image using Kaniko
      ####################################################

      - name: Build And Push
        run: |

          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -v ~/.docker:/kaniko/.docker \
            GHCR_KANIKO_IMAGE_PLACEHOLDER \
            --context=/workspace \
            --dockerfile=/workspace/Dockerfile \
            --destination=${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG}

      ####################################################
      # Summary
      ####################################################

      - name: Build Summary
        run: |
          echo "Image Successfully Generated"
          echo "${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG}"
